// <auto-generated />
using System;
using MainApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MainApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("LabDB.Entity.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "Test",
                            Password = "Test"
                        });
                });

            modelBuilder.Entity("LabDB.Entity.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("LabDB.Entity.LoadedApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ComputerId");

                    b.ToTable("LoadedApps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            ComputerId = 1,
                            DateTime = new DateTime(2022, 12, 11, 15, 44, 52, 407, DateTimeKind.Local).AddTicks(2261),
                            Name = "3D max"
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 1,
                            ComputerId = 1,
                            DateTime = new DateTime(2022, 12, 11, 15, 44, 52, 407, DateTimeKind.Local).AddTicks(2275),
                            Name = "AutoCAD"
                        },
                        new
                        {
                            Id = 3,
                            AgentId = 1,
                            ComputerId = 1,
                            DateTime = new DateTime(2022, 12, 11, 15, 44, 52, 407, DateTimeKind.Local).AddTicks(2277),
                            Name = "Проводник"
                        },
                        new
                        {
                            Id = 4,
                            AgentId = 1,
                            ComputerId = 1,
                            DateTime = new DateTime(2022, 12, 11, 15, 44, 52, 407, DateTimeKind.Local).AddTicks(2279),
                            Name = "Visual Studio 2022"
                        });
                });

            modelBuilder.Entity("LabDB.Entity.LoadedApp", b =>
                {
                    b.HasOne("LabDB.Entity.Agent", "Agent")
                        .WithMany("LoadedApps")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabDB.Entity.Computer", "Computer")
                        .WithMany("LoadedApps")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("LabDB.Entity.Agent", b =>
                {
                    b.Navigation("LoadedApps");
                });

            modelBuilder.Entity("LabDB.Entity.Computer", b =>
                {
                    b.Navigation("LoadedApps");
                });
#pragma warning restore 612, 618
        }
    }
}
